name: Build for dev - android build
on:
  push:
    branches: [main]
jobs:
  android-build:
    name: Dev build android
    runs-on: self-hosted
    steps:
      - name: Host name
        run: hostname
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
      - name: Checkout repo from main branch
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Install npm dependency
        run: yarn install
      - name: Run tests
        run: yarn test --verbose --maxWorkers=2
